baseURL = "http://roblovelett.com/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[author]
    name = "Rob Lovelett"
title = "Rob Lovelett"
theme = "website"
disableHugoGeneratorInject = "true"
relativeURLs = "true"