baseURL = "/"
languageCode = "en-us"
title = "Rob Lovelett's Website"
theme = "site"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
[params]
    description = "A website built with Hugo."
    footer = "[Rob Lovelett](http://roblovelett.com) 2019 | [Github](https://github.com/roblovelett)"