name = "Website"
license = "MIT"
licenselink = "https://github.com/roblovelett/website/LICENSE"
description = "Personal website for Rob Lovelett"
homepage = "http://roblovelett.com"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Rob Lovelett"
  homepage = "http://roblovelett.com"
